name: gizmo_cli
description: A memory editing command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

# This package only works on a Windows machine.
platforms:
  windows:

dependencies:
  path: ^1.8.2
  win32: ^3.1.2
  ffi: '>=1.1.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0
